# == Schema Information
#
# Table name: tasks
#
#  id           :bigint           not null, primary key
#  completed_at :datetime
#  scheduled_at :datetime
#  title        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/tasks', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Task. As you add validations to Task, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    attributes_for(:task)
  end

  let(:invalid_attributes) do
    { title: '' }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Task.create! valid_attributes
      get tasks_url
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_task_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      task = create(:task)
      get edit_task_url(task)
      expect(response).to be_successful
    end

    it 'redirect to index when have invalid id' do
      get edit_task_url('invalid')
      expect(response).to redirect_to(tasks_url)
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Task' do
        expect do
          post tasks_url, params: { task: valid_attributes }
        end.to change(Task, :count).by(1)
      end

      it 'redirects to tasks list' do
        post tasks_url, params: { task: valid_attributes }
        expect(response).to redirect_to(tasks_url)
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Task' do
        expect do
          post tasks_url, params: { task: invalid_attributes }
        end.to change(Task, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post tasks_url, params: { task: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        attributes_for(:task)
      end

      it 'redirects to tasks list' do
        task = create(:task)
        patch task_url(task), params: { task: new_attributes }
        expect(response).to redirect_to(tasks_url)
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        task = create(:task)
        patch task_url(task), params: { task: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested task' do
      task = create(:task)
      expect do
        delete task_url(task)
      end.to change(Task, :count).by(-1)
    end

    it 'redirects to tasks list' do
      task = create(:task)
      delete task_url(task)
      expect(response).to redirect_to(tasks_url)
    end
  end
end
